[package]
name = "Open-Course-Platform"
version = "0.1.0"
authors = ["axel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
