CREATE TABLE sessions (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  slug VARCHAR NOT NULL,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  chapter_id INTEGER NOT NULL REFERENCES chapters (id),
  session_type INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(slug)
)