CREATE TABLE courses (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  description TEXT NOT NULL,
  slug VARCHAR NOT NULL,
  image_link VARCHAR,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(name),
  UNIQUE(slug)
)