CREATE TABLE chapters (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  slug VARCHAR NOT NULL,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  course_id INTEGER NOT NULL REFERENCES courses (id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(slug)
)